mybatis:
  config-location: classpath:mybatis/mybatis-config.xml     # mybatis配置文件所在路径
  type-aliases-package: org.hhxx.ssm.entity                 # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: hhxx 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hhxx?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 971212Zmj
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间